/*
file: portfolioctrl.js
author: amanda falke 2016
*/
export default function PortfolioCtrl($scope,$stateParams)
{
	$scope.projectId = $stateParams.id;

	const id = $scope.id = {}; // object contains models in ctrler for namespacing
	id.id = $scope.projectId;

	$scope.projects = [
		{
			id: 1,
			client: "Black Cobra",
			title: "Invernal",
			synopsis: "Sam Ford was commissioned by Black Cobra for the entirety of the  Invernal  album and merchandise illustration and lettering.",
			description: "Illustration, color, lettering: vinyl LP cover + panels, CD, Japanese LP + panels, and shirts.",
			image: "../images/work/portfolio/opt/portfolio-blackcobra-invernal-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-blackcobra-invernal-opt.jpg",
			link: "https://blackcobrasl.bandcamp.com/album/invernal",
			linkImage: "../images/work/portfolio/thumb-blackcobra-invernal-link.jpg",
			relatedthumb1: "../images/work/thumb-blackcobra-panels.jpg",
			relatedthumb1link: 14,
			relatedthumb2: "../images/work/thumb-black-cobra-japan-cover.jpg",
			relatedthumb2link: 7,
			relatedthumb3: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb3link: 16
		},
		{
			id: 2,
			client: "Agalloch",
			title: "shirt",
			synopsis: "Sam Ford was commissioned by Agalloch for the  Dead Winter Days  tour tshirt.",
			description: "Illustration (black and white): tour tshirt. Lettering by Agalloch.",
			image: "../images/work/portfolio/opt/portfolio-agalloch-deadwinterdays-shirt-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-agalloch-deadwinterdays-shirt-opt.jpg",
			link: "http://www.agalloch.org/",
			linkImage: "../images/work/portfolio/thumb-agalloch-deadwinterdays-shirt.jpg",
			relatedthumb1: "../images/work/thumb-agalloch-deadwinterdays-shirt.jpg",
			relatedthumb1link: 2,
			relatedthumb2: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb2link: 16,
			relatedthumb3: "../images/work/thumb-barrowlands.jpg",
			relatedthumb3link: 12
		},
		{
			id: 3,
			client: "Mountain Goats",
			title: "Tour poster, shirt",
			synopsis: "Sam Ford was commissioned by Mountain Goats for the  Tuttlingen Warriors  2013 tour poster and tshirt merchandising illustration and design.",
			description: "Illustration, color, lettering: Tour poster, tshirt.",
			image: "../images/work/portfolio/opt/portfolio-mountaingoats-poster-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-mountaingoats-poster-opt.jpg",
			link: "http://themountaingoats.wikia.com/wiki/Tuttlingen_Warriors_Tour_2013",
			linkImage: "../images/work/portfolio/thumb-mountaingoats-poster-link.jpg",
			relatedthumb1: "../images/work/thumb-mountain-goats.jpg",
			relatedthumb1link: 3,
			relatedthumb2: "../images/work/thumb-mountain-goats-shirt.jpg",
			relatedthumb2link: 19,
			relatedthumb3: "../images/work/thumb-mountaingoats-shirt-product.jpg",
			relatedthumb3link: 19
		},
		{
			id: 4,
			client: "Cormorant",
			title: "Earth Diver (cover)",
			synopsis: "Sam Ford was commissioned by Cormorant for entirety of  Earth Diver  release and poster.",
			description: "Illustration, color, lettering: LP cover + panels, Deception prerelease tour poster",
			image: "../images/work/portfolio/opt/portfolio-cormorant-earth-diver-cover-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-cormorant-earth-diver-cover-opt.jpg",
			link: "https://cormorant.bandcamp.com/album/earth-diver",
			linkImage: "../images/work/portfolio/thumb-cormorant-earth-diver-link.jpg",
			relatedthumb1: "../images/work/thumb-cormorant-earth-diver-back.jpg",
			relatedthumb1link: 8,
			relatedthumb2: "../images/work/thumb-cormorant-earth-diver-panels.jpg",
			relatedthumb2link: 22,
			relatedthumb3: "../images/work/thumb-cormorant-earthdiver-poster.jpg",
			relatedthumb3link: 17
		},
		{
			id: 5,
			client: "Witch Mountain",
			title: "Mobile of Angels",
			synopsis: "Sam Ford was commissioned by Witch Mountain for the  Mobile of Angels  album cover.",
			description: "Illustration: vinyl LP cover. Coloring by Jason Lewis. Lettering by Witch Mountain.",
			image: "../images/work/portfolio/opt/portfolio-witch-mountain-mobile-of-angels-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-witch-mountain-mobile-of-angels-opt.jpg",
			link: "https://profoundlorerecords.bandcamp.com/album/mobile-of-angels",
			linkImage: "../images/work/portfolio/thumb-witch-mountain-mobile-of-angels.jpg",
			relatedthumb1: "../images/work/thumb-witch-mountain-mobile-of-angels-cover.jpg",
			relatedthumb1link: 5,
			relatedthumb2: "../images/work/thumb-witchmountain-cauldron-of-the-wild.jpg",
			relatedthumb2link: 10,
			relatedthumb3: "../images/work/thumb-witch-mountain-shirt.jpg",
			relatedthumb3link: 21
		},
		{
			id: 6,
			client: "Monarch",
			title: "Omens",
			synopsis: "Sam Ford was commissioned by Monarch for the  Omens  album cover.",
			description: "Illustration, color: vinyl LP cover.",
			image: "../images/work/portfolio/opt/monarch-omens-link-opt.jpg",
			imagexs: "../images/work/portfolio/opt/monarch-omens-link-opt.jpg",
			link: "https://atalossrecordings.merchtable.com/music/vinyl/monarch-omens-vinyl-lp/",
			linkImage: "../images/work/portfolio/thumb-monarch-omens.jpg",
			relatedthumb1: "../images/work/thumb-monarch-omens.jpg",
			relatedthumb1link: 6,
			relatedthumb2: "../images/work/thumb-witch-mountain-shirt.jpg",
			relatedthumb2link: 21,
			relatedthumb3: "../images/work/thumb-wizard-rifle-shirt.jpg",
			relatedthumb3link: 11
		},
		{
			id: 7,
			client: "Black Cobra",
			title: "Invernal (Japan)",
			synopsis: "Sam Ford was commissioned by Black Cobra for the entirety of the  Invernal  album and shirts.",
			description: "Illustration, color, lettering: vinyl LP cover + panels, CD, separate Japan release with traditional panel artwork, shirts.",
			image: "../images/work/portfolio/opt/portfolio-blackcobra-japan-cover-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-blackcobra-japan-cover-opt.jpg",
			link: "https://blackcobrasl.bandcamp.com/album/invernal",
			linkImage: "../images/work/portfolio/thumb-blackcobra-invernal-link.jpg",
			relatedthumb1: "../images/work/thumb-black-cobra-invernal-cover-lettering.jpg",
			relatedthumb1link: 1,
			relatedthumb2: "../images/work/thumb-blackcobra-panels.jpg",
			relatedthumb2link: 14,
			relatedthumb3: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb3link: 16
		},
		{
			id: 8,
			client: "Cormorant",
			title: "Earth Diver (back cover)",
			synopsis: "Sam Ford was commissioned by Cormorant for entirety of  Earth Diver  release and poster.",
			description: "Illustration, color, lettering: LP cover + panels, Deception prerelease tour poster",
			image: "../images/work/portfolio/opt/portfolio-cormorant-earth-diver-back-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-cormorant-earth-diver-back-opt.jpg",
			link: "https://cormorant.bandcamp.com/album/earth-diver",
			linkImage: "../images/work/portfolio/thumb-cormorant-earth-diver-link.jpg",
			relatedthumb1: "../images/work/thumb-cormorant-earth-diver.jpg",
			relatedthumb1link: 4,
			relatedthumb2: "../images/work/thumb-cormorant-earth-diver-panels.jpg",
			relatedthumb2link: 22,
			relatedthumb3: "../images/work/thumb-cormorant-earthdiver-poster.jpg",
			relatedthumb3link: 17
		},
		{
			id: 9,
			client: "Burnt Books",
			title: "s/t",
			synopsis: "Sam Ford was commissioned by Burnt Books for their self titled album cover.",
			description: "Illustration, color, lettering: vinyl LP cover.",
			image: "../images/work/portfolio/opt/portfolio-burntbooks-st-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-burntbooks-st-opt.jpg",
			link: "http://www.invisibleoranges.com/io-exclusive-album-stream-burnt-books-st/",
			linkImage: "../images/work/portfolio/thumb-burntbooks-st-link.jpg",
			relatedthumb3: "../images/work/thumb-turbo.jpg",
			relatedthumb3link: 18,
			relatedthumb1: "../images/work/thumb-burnt-books.jpg",
			relatedthumb1link: 9,
			relatedthumb2: "../images/work/thumb-thrones.jpg",
			relatedthumb2link: 15
		},
		{
			id: 10,
			client: "Witch Mountain",
			title: "Cauldron of the Wild",
			synopsis: "Sam Ford was commissioned by Witch Mountain for the  Cauldron of the Wild  album cover.",
			description: "Illustration: vinyl LP cover. Coloring by Jason Lewis. Lettering by Witch Mountain.",
			image: "../images/work/portfolio/opt/portfolio-witchmountain-cauldron-of-the-wild-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-witchmountain-cauldron-of-the-wild-opt.jpg",
			link: "https://witchmountain.bandcamp.com/album/cauldron-of-the-wild",
			linkImage: "../images/work/portfolio/thumb-witchmountain-cauldron-of-the-wild.jpg",
			relatedthumb1: "../images/work/thumb-witchmountain-cauldron-of-the-wild.jpg",
			relatedthumb1link: 10,
			relatedthumb2: "../images/work/thumb-witch-mountain-shirt.jpg",
			relatedthumb2link: 21,
			relatedthumb3: "../images/work/thumb-witch-mountain-mobile-of-angels-cover.jpg",
			relatedthumb3link: 5
		},
		{
			id: 11,
			client: "Wizard Rifle",
			title: "Wizard Rifle  Blood  T-Shirt",
			synopsis: "Sam Ford drums - and draws - in Wizard Rifle.",
			image: "../images/work/portfolio/opt/portfolio-wizard-rifle-blood-shirt-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-wizard-rifle-blood-shirt-opt.jpg",
			link: "http://releases.seventhrule.com/album/speak-loud-say-nothing",
			linkImage: "../images/work/portfolio/thumb-wizard-rifle-blood-shirt.jpg",
			relatedthumb1: "../images/work/thumb-wizard-rifle-shirt.jpg",
			relatedthumb1link: 11,
			relatedthumb2: "../images/work/thumb-wizardrifle-speak.jpg",
			relatedthumb2link: 28,
			relatedthumb3: "../images/work/portfolio/thumb-wizard-rifle-logo-shirt.jpg",
			relatedthumb3link: 30
		},
		{
			id: 12,
			client: "Barrowlands",
			title: "Thane",
			synopsis: "Sam Ford was commissioned by Barrowlands for the  Thane  album cover and t-shirts.",
			description: "Illustration (black and white): vinyl LP, shirts.",
			image: "../images/work/portfolio/opt/portfolio-barrowlands-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-barrowlands-opt.jpg",
			link: "https://barrowlands.bandcamp.com/album/thane",
			linkImage: "../images/work/portfolio/thumb-barrowlands.jpg",
			relatedthumb3: "../images/work/thumb-agalloch-deadwinterdays-shirt.jpg",
			relatedthumb3link: 2,
			relatedthumb2: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb2link: 16,
			relatedthumb1: "../images/work/thumb-barrowlands.jpg",
			relatedthumb1link: 12
		},
		{
			id: 13,
			client: "Diesto",
			title: "High As The Sun",
			synopsis: "Sam Ford was commissioned by Diesto for the  High As The Sun  album.",
			description: "Illustration, lettering: Vinyl LP. Coloring by Kirk Evans",
			image: "../images/work/portfolio/opt/portfolio-diesto-high-as-the-sun-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-diesto-high-as-the-sun-opt.jpg",
			link: "http://releases.seventhrule.com/album/high-as-the-sun",
			linkImage: "../images/work/portfolio/thumb-diesto-high-as-the-sun.jpg",
			relatedthumb1: "../images/work/thumb-diesto-high-as-the-sun.jpg",
			relatedthumb1link: 13,
			relatedthumb2: "../images/work/thumb-diesto-for-water-or-blood.jpg",
			relatedthumb2link: 20,
			relatedthumb3: "../images/work/thumb-thrones.jpg",
			relatedthumb3link: 15
		},
		{
			id: 14,
			client: "Black Cobra",
			title: "Invernal (interior panels)",
			synopsis: "Sam Ford was commissioned by Black Cobra for the entirety of the  Invernal  album and merchandise.",
			description: "Illustration, color, lettering: vinyl LP cover + panels, CD, Japanese LP + panels, and shirts.",
			image: "../images/work/portfolio/opt/portfolio-blackcobra-invernal-panels-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-blackcobra-invernal-panels-opt.jpg",
			link: "https://blackcobrasl.bandcamp.com/album/invernal",
			linkImage: "../images/work/portfolio/thumb-blackcobra-invernal-link.jpg",
			relatedthumb1: "../images/work/thumb-black-cobra-invernal-cover-lettering.jpg",
			relatedthumb1link: 1,
			relatedthumb2: "../images/work/thumb-black-cobra-japan-cover.jpg",
			relatedthumb2link: 7,
			relatedthumb3: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb3link: 16
		},
		{
			id: 15,
			client: "Thrones/Sedan",
			title: "When It s Teamwork, It Doesn t Seem Work (split)",
			synopsis: "Sam Ford commission",
			description: "Illustration + color: Vinyl LP. The illustration work was based on an original painting by Johfra Bosschart, per the clients.",
			image: "../images/work/portfolio/opt/portfolio-thrones-sedan-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-thrones-sedan-opt.jpg",
			link: "https://sedan.bandcamp.com/album/when-its-teamwork-it-doesnt-seem-work",
			linkImage: "../images/work/portfolio/thumb-thrones-sedan.jpg",
			relatedthumb3: "../images/work/thumb-turbo.jpg",
			relatedthumb3link: 18,
			relatedthumb2: "../images/work/thumb-burnt-books.jpg",
			relatedthumb2link: 9,
			relatedthumb1: "../images/work/thumb-thrones.jpg",
			relatedthumb1link: 15
		},
		{
			id: 16,
			client: "Black Cobra",
			title: "Invernal (Japan) - Panels",
			synopsis: "Sam Ford was commissioned by Black Cobra for the entirety of the  Invernal  album and merchandise.",
			description: "Illustration, color, lettering: vinyl LP cover + panels, CD, Japanese LP + panels, shirts.",
			image: "../images/work/portfolio/opt/portfolio-blackcobra-japan-panels-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-blackcobra-japan-panels-opt.jpg",
			link: "https://blackcobrasl.bandcamp.com/album/invernal",
			linkImage: "../images/work/portfolio/thumb-blackcobra-invernal-link.jpg",
			relatedthumb1: "../images/work/thumb-blackcobra-panels.jpg",
			relatedthumb1link: 14,
			relatedthumb2: "../images/work/thumb-black-cobra-japan-cover.jpg",
			relatedthumb2link: 7,
			relatedthumb3: "../images/work/thumb-black-cobra-invernal-cover-lettering.jpg",
			relatedthumb3link: 1
		},
		{
			id: 17,
			client: "Cormorant",
			title: "Earth Diver Deception Poster",
			synopsis: "Sam Ford was commissioned by Cormorant for entirety of  Earth Diver  release and poster.",
			description: "Illustration, color, lettering: LP cover + panels, Deception prerelease tour poster",
			image: "../images/work/portfolio/opt/portfolio-cormorant-earth-diver-poster-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-cormorant-earth-diver-poster-opt.jpg",
			link: "https://cormorant.bandcamp.com/album/earth-diver",
			linkImage: "../images/work/portfolio/thumb-cormorant-earth-diver-link.jpg",
			relatedthumb1: "../images/work/thumb-cormorant-earth-diver-back.jpg",
			relatedthumb1link: 8,
			relatedthumb2: "../images/work/thumb-cormorant-earth-diver.jpg",
			relatedthumb2link: 4,
			relatedthumb3: "../images/work/thumb-cormorant-earth-diver-panels.jpg",
			relatedthumb3link: 22
		},
		{
			id: 18,
			client: "Turbo Lightning",
			title: "s/t",
			synopsis: "Sam Ford was commissioned by Turbo Lightning for full jacket LP album illustration and design.",
			description: "Illustration: vinyl LP jacket + cassette.",
			image: "../images/work/portfolio/opt/portfolio-turbo-lightning-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-turbo-lightning-opt.jpg",
			link: "https://turbolightning.bandcamp.com/album/faster-than-light",
			linkImage: "../images/work/portfolio/thumb-turbo.jpg",
			relatedthumb1: "../images/work/thumb-turbo.jpg",
			relatedthumb1link: 18,
			relatedthumb2: "../images/work/thumb-burnt-books.jpg",
			relatedthumb2link: 9,
			relatedthumb3: "../images/work/thumb-thrones.jpg",
			relatedthumb3link: 15
		},
		{
			id: 19,
			client: "Mountain Goats",
			title: "2013 tour tshirt",
			synopsis: "Sam Ford was commissioned by Mountain Goats for the Tuttlingen Warriors 2013 tour poster and tshirt merchandising illustration and design.",
			description: "Illustration, color, lettering: Tour poster, tshirt.",
			image: "../images/work/portfolio/opt/portfolio-mountaingoats-shirt-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-mountaingoats-shirt-opt.jpg",
			link: "http://themountaingoats.wikia.com/wiki/Tuttlingen_Warriors_Tour_2013",
			linkImage: "../images/work/portfolio/thumb-mountaingoats-poster-link.jpg",
			relatedthumb1: "../images/work/thumb-mountain-goats-shirt.jpg",
			relatedthumb1link: 19,
			relatedthumb3: "../images/work/thumb-mountain-goats.jpg",
			relatedthumb3link: 3,
			relatedthumb2: "../images/work/thumb-mountaingoats-shirt-product.jpg",
			relatedthumb2link: 3
		},
		{
			id: 20,
			client: "Diesto",
			title: "For Water Or Blood",
			synopsis: "Sam Ford was commissioned by Diesto for the  For Water Or Blood  album.",
			description: "Illustration, color, lettering: Vinyl LP.",
			image: "../images/work/portfolio/opt/portfolio-diesto-for-water-or-blood-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-diesto-for-water-or-blood-opt.jpg",
			link: "http://digital.eolianempire.com/album/for-water-or-blood",
			linkImage: "../images/work/portfolio/thumb-diesto-for-water-or-blood.jpg",
			relatedthumb1: "../images/work/thumb-diesto-for-water-or-blood.jpg",
			relatedthumb1link: 20,
			relatedthumb2: "../images/work/thumb-diesto-high-as-the-sun.jpg",
			relatedthumb2link: 13,
			relatedthumb3: "../images/work/thumb-thrones.jpg",
			relatedthumb3link: 15
		},
		{
			id: 21,
			client: "Witch Mountain",
			title: "Alien Eagle T-Shirt",
			synopsis: "Sam Ford was commissioned by Witch Mountain for the Alien Eagle shirt.",
			description: "Illustration: Alien Eagle T-Shirt.",
			image: "../images/work/portfolio/opt/portfolio-witch-mountain-shirt-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-witch-mountain-shirt-opt.jpg",
			link: "https://witchmountain.bandcamp.com/merch/alien-eagle-t-shirt-designed-by-sam-ford",
			linkImage: "../images/work/portfolio/thumb-witch-mountain-shirt.jpg",
			relatedthumb1: "../images/work/thumb-witch-mountain-shirt.jpg",
			relatedthumb1link: 21,
			relatedthumb2: "../images/work/thumb-witchmountain-cauldron-of-the-wild.jpg",
			relatedthumb2link: 10,
			relatedthumb3: "../images/work/thumb-witch-mountain-mobile-of-angels-cover.jpg",
			relatedthumb3link: 5
		},
		{
			id: 22,
			client: "Cormorant",
			title: "Earth Diver, Panels",
			synopsis: "Sam Ford was commissioned by Cormorant for entirety of  Earth Diver  release and poster.",
			description: "Illustration, color, lettering: LP cover + panels, Deception prerelease tour poster",
			image: "../images/work/portfolio/opt/portfolio-cormorant-earth-diver-panels-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-cormorant-earth-diver-panels-opt.jpg",
			link: "https://cormorant.bandcamp.com/album/earth-diver",
			linkImage: "../images/work/portfolio/thumb-cormorant-earth-diver-link.jpg",
			relatedthumb1: "../images/work/thumb-cormorant-earth-diver-back.jpg",
			relatedthumb1link: 8,
			relatedthumb2: "../images/work/thumb-cormorant-earth-diver.jpg",
			relatedthumb2link: 4,
			relatedthumb3: "../images/work/thumb-cormorant-earthdiver-poster.jpg",
			relatedthumb3link: 17
		},
		{
			id: 23,
			client: "Nether Regions",
			title: "Album cover illustration",
			synopsis: "Sam Ford was commissioned by Nether Regions for release",
			description: "Illustration, color, lettering: LP cover",
			image: "../images/work/portfolio/opt/portfolio-netherregions-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-netherregions-opt.jpg",
			link: "https://netherregions.bandcamp.com/",
			linkImage: "../images/work/portfolio/thumb-netherregions.jpg",
			relatedthumb1: "../images/work/thumb-nether-regions.jpg",
			relatedthumb1link: 23,
			relatedthumb2: "../images/work/thumb-monarch-omens.jpg",
			relatedthumb2link: 6,
			relatedthumb3: "../images/work/thumb-witch-mountain-shirt.jpg",
			relatedthumb3link: 21
		},
		{
			id: 24,
			client: "Al the dog",
			title: "Tattoo",
			description: "Sam Ford tattoo commissions",
			synopsis: "Tattoo for a friend.",
			image: "../images/work/portfolio/opt/portfolio-al-tattoo-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-al-tattoo-opt.jpg",
			relatedthumb1: "../images/work/thumb-al-tattoo.jpg",
			relatedthumb1link: 24,
			relatedthumb2: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb2link: 16,
			relatedthumb3: "../images/work/thumb-barrowlands.jpg",
			relatedthumb3link: 12
		},
		{
			id: 25,
			client: "Norilsk",
			title: "Idea of North",
			synopsis: "Sam Ford was commissioned by Norilsk for  Idea of North  release.",
			description: "Illustration, color, lettering: cassette + CD Digipak + booklet illustration",
			image: "../images/work/portfolio/opt/portfolio-norilsk-idea-of-north-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-norilsk-idea-of-north-opt.jpg",
			link: "https://norilskdoom.bandcamp.com/album/the-idea-of-north",
			linkImage: "../images/work/portfolio/thumb-norilsk-idea-of-north.jpg",
			relatedthumb1: "../images/work/thumb-norilsk.jpg",
			relatedthumb1link: 29,
			relatedthumb2: "../images/work/thumb-nether-regions.jpg",
			relatedthumb2link: 23,
			relatedthumb3: "../images/work/thumb-monarch-omens.jpg",
			relatedthumb3link: 6
		},
		{
			id: 26,
			client: "Black Cobra",
			title: "shirt",
			synopsis: "Sam Ford was commissioned by Black Cobra for the entirety of the  Invernal  album and merchandise illustration and lettering.",
			description: "Illustration, color, lettering: vinyl LP cover + panels, CD, Japanese LP + panels, and shirts.",
			image: "../images/work/portfolio/opt/portfolio-bc-shirt-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-bc-shirt-opt.jpg",
			link: "https://blackcobrasl.bandcamp.com/album/invernal",
			linkImage: "../images/work/portfolio/thumb-bc-shirt.jpg",
			relatedthumb1: "../images/work/thumb-blackcobra-panels.jpg",
			relatedthumb1link: 14,
			relatedthumb2: "../images/work/thumb-black-cobra-japan-cover.jpg",
			relatedthumb2link: 7,
			relatedthumb3: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb3link: 16
		},
		{
			id: 27,
			client: "Jeremy C Long",
			synopsis: "Sam Ford commission",
			title: "Lepidoptera LP cover",
			description: "Illustration: vinyl LP.",
			image: "../images/work/portfolio/opt/portfolio-lepidoptera-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-lepidoptera-opt.jpg",
			link: "https://jeremylong.bandcamp.com/album/lepidoptera",
			linkImage: "../images/work/portfolio/thumb-lepidoptera.jpg",
			relatedthumb3: "../images/work/thumb-agalloch-deadwinterdays-shirt.jpg",
			relatedthumb3link: 2,
			relatedthumb2: "../images/work/thumb-blackcobra-invernal-japan-panels.jpg",
			relatedthumb2link: 16,
			relatedthumb1: "../images/work/thumb-lepidoptera.jpg",
			relatedthumb1link: 27
		},
		{
			id: 28,
			client: "Wizard Rifle",
			title: "Speak Loud, Say Nothing",
			description: "Sam Ford drums - and draws - in Wizard Rifle.",
			image: "../images/work/portfolio/opt/portfolio-wizardrifle-speak-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-wizardrifle-speak-opt.jpg",
			link: "http://releases.seventhrule.com/album/speak-loud-say-nothing",
			linkImage: "../images/work/portfolio/thumb-wizardrifle-speak.jpg",
			relatedthumb1: "../images/work/thumb-wizardrifle-speak.jpg",
			relatedthumb1link: 28,
			relatedthumb2: "../images/work/thumb-wizard-rifle-logo-shirt.jpg",
			relatedthumb2link: 30,
			relatedthumb3: "../images/work/thumb-wizard-rifle-shirt.jpg",
			relatedthumb3link: 11
		},
		{
			id: 29,
			client: "Fuming Mouth/Gatlin",
			title: "split 7",
			synopsis: "Sam Ford commission",
			description: "Illustration (black and white): vinyl LP cover.",
			image: "../images/work/portfolio/opt/portfolio-fuming-mouth-gatlin-opt.jpg",
			imagexs: "../images/work/portfolio/opt/xs-portfolio-fuming-mouth-gatlin-opt.jpg",
			link: "https://fumingmouth.bandcamp.com/album/fuming-mouth-gatlin-split-7",
			linkImage: "../images/work/portfolio/thumb-fuming-mouth-gatlin.jpg",
			relatedthumb2: "../images/work/thumb-agalloch-deadwinterdays-shirt.jpg",
			relatedthumb2link: 2,
			relatedthumb1: "../images/work/thumb-fuming-mouth-gatlin.jpg",
			relatedthumb1link: 29,
			relatedthumb3: "../images/work/thumb-barrowlands.jpg",
			relatedthumb3link: 12
		},
		{
			id: 30,
			client: "Wizard Rifle",
			title: "logo shirt",
			description: "Sam Ford drums - and draws - in Wizard Rifle.",
			image: "../images/work/portfolio/opt/portfolio-wizard-rifle-logo-shirt-opt.jpg",
			imagexs: "../images/work/portfolio/opt/portfolio-wizard-rifle-logo-shirt-opt.jpg",
			link: "http://releases.seventhrule.com/album/speak-loud-say-nothing",
			linkImage: "../images/work/portfolio/thumb-wizard-rifle-logo-shirt.jpg",
			relatedthumb1: "../images/work/thumb-wizard-rifle-logo-shirt.jpg",
			relatedthumb1link: 30,
			relatedthumb2: "../images/work/thumb-wizard-rifle-shirt.jpg",
			relatedthumb2link: 11,
			relatedthumb3: "../images/work/thumb-wizardrifle-speak.jpg",
			relatedthumb3link: 28
		}
	];

	const portfolioNextPrev = () => {

		id.prev = id.id;
		parseInt((--id.prev),10);
		id.next = id.id;
		parseInt((++id.next),10);

		$scope.len = $scope.projects.length;

		// At the beginning, prev goes to end (last item).
		if(id.prev == 0)
		{
			id.prev = $scope.len;
		}
		// At the end, next goes to beginning (first item).
		else if(id.next > $scope.len)
		{
			id.next = 1;
		}
	};

	portfolioNextPrev();

}
